const foodItems = [
  // --- RESTAURANTS (10) ---
  {
    id: 1,
    title: "Pizza Carrée & Coca",
    donor: "Pizzeria L'Etna",
    type: "Restaurant",
    foodType: "Fast Food",
    price: 600,
    originalPrice: 1200,
    image: "assets/images/pizza-carrez.jpg",
    location: "8 Bd de la Soummam, Oran",
    timeLeft: "4 hours",
    description: "بيتزا مربعة تقليدية مع صلصة طماطم غنية وجبن موزاريلا، تقدم مع مشروب كوكا كولا بارد.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 2,
    title: "Couscous Royal",
    donor: "Restaurant Le Nautique",
    type: "Restaurant",
    foodType: "Traditional",
    price: 1800,
    originalPrice: 4500,
    image: "assets/images/couscous-royal.jpg",
    location: "Route du Cap de Garde, Annaba",
    timeLeft: "30 mins",
    description: "كسكسي ملكي جزائري مع تشكيلة من اللحوم الطازجة والخضروات الموسمية، مطهو على الطريقة التقليدية.",
    promoted: true,
    paymentMethods: ["CIB", "BaridiMob"],
  },
  {
    id: 3,
    title: "Traditional Algerian Dinner",
    donor: "Restaurant El Djenina",
    type: "Restaurant",
    foodType: "Traditional",
    price: 2500,
    originalPrice: 5500,
    image: "assets/images/traditonal-dinnerr.jpg",
    location: "8 Rue Franklin Roosevelt, Algiers",
    timeLeft: "1 hour",
    description: "عشاء جزائري متكامل يضم طبقاً رئيسياً مع شوربة فريك أصيلة، محضر بعناية ليعكس نكهات العاصمة.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 4,
    title: "Gourmet Burger Combo",
    donor: "Le Tantra Restaurant",
    type: "Restaurant",
    foodType: "Fast Food",
    price: 900,
    originalPrice: 1800,
    image: "assets/images/Gourmet-Burger-Combo.jpg",
    location: "Sidi Yahia, Algiers",
    timeLeft: "2 hours",
    description: "وجبة برجر فاخرة من لحم البقر الطازج مع بطاطس مقرمشة ومشروب، تجربة عصرية بنكهة مميزة.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 5,
    title: "Syrian Mezze Platter",
    donor: "Restaurant Arabesque",
    type: "Restaurant",
    foodType: "Traditional",
    price: 1200,
    originalPrice: 2800,
    image: "assets/images/Syrian-Mezze-Platter.jpg",
    location: "Avenue de l'Indépendance, Algiers",
    timeLeft: "3 hours",
    description: "تشكيلة غنية من المقبلات الشامية الأصيلة تشمل الحمص، المتبل، والفلافل الساخنة.",
    promoted: false,
    paymentMethods: ["Cash", "BaridiMob"],
  },
  {
    id: 6,
    title: "Seafood Platter Oranais",
    donor: "Restaurant El Firdaous",
    type: "Restaurant",
    foodType: "Traditional",
    price: 3200,
    originalPrice: 7000,
    image: "assets/images/Seafood-Platter-Oranais.jpg",
    location: "Front de Mer, Oran",
    timeLeft: "1.5 hours",
    description: "طبق فواكه البحر الوهراني الطازج، مشوي على الجمر مع تتبيلة الأعشاب المتوسطية.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 7,
    title: "Indian Curry Box",
    donor: "Maharaja Restaurant",
    type: "Restaurant",
    foodType: "Traditional",
    price: 1500,
    originalPrice: 3200,
    image: "assets/images/Indian-Curry-Box.jpg",
    location: "Canastel, Oran",
    timeLeft: "2 hours",
    description: "بوكس الكاري الهندي مع دجاج الزبدة (Butter Chicken) الشهير، يقدم مع أرز بسمتي وخبز النان.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 8,
    title: "Constantinois Chakhchoukha",
    donor: "Igherssan Restaurant",
    type: "Restaurant",
    foodType: "Traditional",
    price: 1100,
    originalPrice: 2500,
    image: "assets/images/Constantinois-Chakhchoukha.jpg",
    location: "Vieux Constantine, Constantine",
    timeLeft: "3 hours",
    description: "شخشوخة قسنطينية أصيلة محضرة بعجينة مرققة يدوياً مع مرق أحمر غني ولحم مطهو ببطء.",
    promoted: true,
    paymentMethods: ["Cash", "BaridiMob"],
  },
  {
    id: 9,
    title: "traditional Seafood Paella",
    donor: "Restaurant Tabarka",
    type: "Restaurant",
    foodType: "Traditional",
    price: 2000,
    originalPrice: 4500,
    image: "assets/images/traditional-seafood-paella.jpg",
    location: "Corniche, Annaba",
    timeLeft: "4 hours",
    description: "بايلة ثمار البحر التقليدية الغنية بالأرز المزعفر وتشكيلة من أجود أنواع الأسماك والمحار.",
    promoted: false,
    paymentMethods: ["CIB"],
  },
  {
    id: 10,
    title: "Mainama of Illizi",
    donor: "Restaurant Tassili",
    type: "Restaurant",
    foodType: "Traditional",
    price: 1300,
    originalPrice: 3000,
    image: "assets/images/Mainama-iIlizi.jpg",
    location: "Centre Ville, Illizi",
    timeLeft: "5 hours",
    description: "طبق الماينمة الأصيل من ولاية إليزي، تجربة فريدة من أعماق الصحراء الجزائرية.",
    promoted: true,
    paymentMethods: ["Cash", "BaridiMob"],
  },

  // --- HOTELS (10) ---
  {
    id: 11,
    title: "Breakfast Buffet Surplus",
    donor: "Constantine Marriott Hotel",
    type: "Hotel",
    foodType: "Traditional",
    price: 800,
    originalPrice: 2000,
    image: "assets/images/breakfast-set-egg-with-sausages-side-view.jpg",
    location: "Cité universitaire Zouaghi, Constantine",
    timeLeft: "1 hour",
    description: "تشكيلة غنية من مائدة الإفطار الفاخرة بفندق ماريوت، تشمل معجنات فرنسية، بيض، وأطباق قسنطينية تقليدية.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB", "Cash"],
  },
  {
    id: 12,
    title: "Luxury Pastry Box",
    donor: "Sofitel Algiers Hamma Garden",
    type: "Hotel",
    foodType: "Desserts",
    price: 1800,
    originalPrice: 4000,
    image: "assets/images/Luxury-Pastry-Box.jpg",
    location: "Rue Hassiba Ben Bouali, Algiers",
    timeLeft: "2 hours",
    description: "علبة حلويات فاخرة من تحضير طهاة صوفيتيل، تضم تشكيلة مختارة من الحلويات الفرنسية والجزائرية العصرية.",
    promoted: true,
    paymentMethods: ["CIB", "BaridiMob"],
  },
  {
    id: 13,
    title: "English Tea Sandwich Box",
    donor: "Hyatt Regency Algiers",
    type: "Hotel",
    foodType: "Fast Food",
    price: 1200,
    originalPrice: 2800,
    image: "assets/images/English-Tea Sandwich-Box.jpg",
    location: "Algiers Airport, Algiers",
    timeLeft: "3 hours",
    description: "مجموعة مختارة من السندوتشات الخفيفة بأسلوب الشاي الإنجليزي، مثالية لوجبة خفيفة سريعة وعالية الجودة.",
    promoted: false,
    paymentMethods: ["Cash", "CIB"],
  },
  {
    id: 14,
    title: "Seafood Buffet Special",
    donor: "Sheraton Club des Pins",
    type: "Hotel",
    foodType: "Healthy",
    price: 3500,
    originalPrice: 8500,
    image: "assets/images/sheraton-club-pins-seafood.jpg",
    location: "Club des Pins, Algiers",
    timeLeft: "1 hour",
    description: "أطباق بحرية فاخرة متبقية من بوفيه العشاء البحري في شيراتون، تشمل الجمبري والأسماك المشوية.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 15,
    title: "Gourmet Mediterranean Box",
    donor: "Royal Hotel Oran",
    type: "Hotel",
    foodType: "Healthy",
    price: 2200,
    originalPrice: 5000,
    image: "assets/images/Gourmet-Mediterranean-Box.jpg",
    location: "1 Boulevard de la Soummam, Oran",
    timeLeft: "2 hours",
    description: "وجبة متوسطية فاخرة من مطعم فندق رويال وهران التاريخي، تضم أطباقاً رئيسية ومقبلات راقية.",
    promoted: false,
    paymentMethods: ["Cash", "BaridiMob"],
  },
  {
    id: 16,
    title: "International Cuisine Box",
    donor: "Le Méridien Oran",
    type: "Hotel",
    foodType: "Traditional",
    price: 2800,
    originalPrice: 6000,
    image: "assets/images/International-Cuisin-Box.jpg",
    location: "Les Falaises, Oran",
    timeLeft: "4 hours",
    description: "تذوق نكهات العالم مع علبة المأكولات العالمية من فندق الميريديان، مزيج من الأطباق الآسيوية والأوروبية.",
    promoted: true,
    paymentMethods: ["CIB"],
  },
  {
    id: 17,
    title: "Moukabilat",
    donor: "Sheraton Annaba Hotel",
    type: "Hotel",
    foodType: "Traditional",
    price: 2500,
    originalPrice: 5500,
    image: "assets/images/Moukabilat.jpg",
    location: "Boulevard Rizzi Amor, Annaba",
    timeLeft: "1.5 hours",
    description: "مقبلات ومملحات فاخرة من تراس فندق شيراتون عنابة، مثالية للاستمتاع بنكهات بحرية خفيفة.",
    promoted: false,
    paymentMethods: ["Cash", "BaridiMob"],
  },
  {
    id: 18,
    title: "Royal Tlemcen Dinner",
    donor: "Renaissance Tlemcen Hotel",
    type: "Hotel",
    foodType: "Traditional",
    price: 3000,
    originalPrice: 7000,
    image: "assets/images/Royal-Tlemcen-Dinner.jpg",
    location: "Lalla Setti, Tlemcen",
    timeLeft: "2 hours",
    description: "عشاء تلمساني ملكي من فندق رينيسانس، يضم أطباقاً تقليدية عريقة تم تحضيرها لمناسبات خاصة.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 19,
    title: "Coastal Luxury Brunch",
    donor: "Royal Tulip Skikda",
    type: "Hotel",
    foodType: "Healthy",
    price: 2600,
    originalPrice: 6500,
    image: "assets/images/Coastal-Luxury-Brunch.jpg",
    location: "Plage Larbi Ben M'hidi, Skikda",
    timeLeft: "3 hours",
    description: "تشكيلة برانش (Brunch) فاخرة متبقية من الخدمة الصباحية، تضم خيارات صحية ولذيذة من خيرات البحر والبر.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 20,
    title: "Kabylie Forest Harvest Bed",
    donor: "SALDAE Hotel & Spa",
    type: "Hotel",
    foodType: "Traditional",
    price: 1500,
    originalPrice: 5000,
    image: "assets/images/Gourmet-Mediterranean-Box.jpg",
    location: "1 Boulevard de la Soummam, Oran",
    timeLeft: "5 hours",
    description: "إفطار بجاوي أصيل يضم زيت الزيتون، العسل، والخبز التقليدي من خيرات منطقة القبائل الكبرى.",
    promoted: true,
    paymentMethods: ["Cash", "BaridiMob"],
  },

  // --- BAKERIES (10) ---
  {
    id: 21,
    title: "Plateau Gâteaux Traditionnels",
    donor: "Maison Amoud",
    type: "Bakery",
    foodType: "Desserts",
    price: 1500,
    originalPrice: 2500,
    image: "assets/images/traditional-azerbaijan-pastries-shakarbura-bakhlava-plate.jpg",
    location: "Sidi Yahia, Algiers",
    timeLeft: "2 hours",
    description: "صحن مشكل من الحلويات التقليدية (بقلاوة، مقروط، تشارك) محضر يدوياً بكل إتقان.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 22,
    title: "Matlouh & Kesra",
    donor: "Boulangerie El Baraka",
    type: "Bakery",
    foodType: "Bakery",
    price: 200,
    originalPrice: 500,
    image: "assets/images/Matlouh-Kesra.jpg",
    location: "El Eulma, Sétif",
    timeLeft: "3 hours",
    description: "مجموعة من خبز المطلوع والكسرة الساخنة، محضرة بالسميد ومخبوزة في فرن تقليدي.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 23,
    title: "Millefeuille & Tart Box",
    donor: "Pâtisserie Espérance",
    type: "Bakery",
    foodType: "Desserts",
    price: 700,
    originalPrice: 1500,
    image: "assets/images/Millefeuille-Tart-Box.jpg",
    location: "Place Maurice Audin, Algiers",
    timeLeft: "1 hour",
    description: "تشكيلة من الحلويات الفرنسية الراقية تشمل الملفاي وتارت الفواكه الطازجة.",
    promoted: true,
    paymentMethods: ["Cash"],
  },
  {
    id: 24,
    title: "Oran Gateau Sec Box",
    donor: "Pâtisserie Rahma",
    type: "Bakery",
    foodType: "Desserts",
    price: 500,
    originalPrice: 1200,
    image: "assets/images/Oran-Gateau-Sec-Box.jpg",
    location: "Place d'Armes, Oran",
    timeLeft: "4 hours",
    description: "علبة حلويات جافة تقليدية وكرون (Cornnes) من الطابع الوهراني الأصيل.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 25,
    title: "Artisan Baguette Mix",
    donor: "Boulangerie La Parisienne",
    type: "Bakery",
    foodType: "Bakery",
    price: 300,
    originalPrice: 800,
    image: "assets/images/baguettes-market-france-close-up.jpg",
    location: "Hydra, Algiers",
    timeLeft: "2 hours",
    description: "مجموعة مختارة من خبز الباغيت الحرفي المخبوز بالحبوب الكاملة والسمن الطبيعي.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 26,
    title: "Breakfast Croissant Pack",
    donor: "Le Croissant Doré",
    type: "Bakery",
    foodType: "Bakery",
    price: 400,
    originalPrice: 1000,
    image: "assets/images/Breakfast-Croissant-Pack.jpg",
    location: "Cours de la Révolution, Annaba",
    timeLeft: "3 hours",
    description: "حزمة من الكرواسون الهش وخبز الشوكولاتة المحضر بالزبدة الطبيعية.",
    promoted: true,
    paymentMethods: ["BaridiMob"],
  },
  {
    id: 27,
    title: "Oriental Sweets Assortment",
    donor: "Pâtisserie Orientale Z'hor",
    type: "Bakery",
    foodType: "Desserts",
    price: 1800,
    originalPrice: 3500,
    image: "assets/images/Oriental-Sweets-Assortment.jpg",
    location: "Sidi Mabrouk, Constantine",
    timeLeft: "5 hours",
    description: "تشكيلة من حلويات قسنطينة الشرقية الشهيرة بما فيها الشبية والحلويات المعسلة.",
    promoted: true,
    paymentMethods: ["Cash", "BaridiMob"],
  },
  {
    id: 28,
    title: "Traditional Ghardaïa Bread",
    donor: "Boulangerie Traditionnelle",
    type: "Bakery",
    foodType: "Bakery",
    price: 150,
    originalPrice: 400,
    image: "assets/images/delicious-pita-pakistan-food.jpg",
    location: "Ksar de Ghardaïa, Ghardaïa",
    timeLeft: "2 hours",
    description: "خبز صحراوي تقليدي مخبوز في أفران طينية، يتميز بنكهته العميقة وقيمته الغذائية العالية.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 29,
    title: "Tlemcen Almond Sweets",
    donor: "Pâtisserie Moderne",
    type: "Bakery",
    foodType: "Desserts",
    price: 2200,
    originalPrice: 7000,
    image: "assets/images/nougats-plate-still-life-top-view.jpg",
    location: "Lalla Setti, Tlemcen",
    timeLeft: "4 hours",
    description: "حلويات لوز راقية من قلب تلمسان، تضم أنواعاً مخبوزة باللوز والعسل الطبيعي.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 30,
    title: "Fresh Matlouh Hub",
    donor: "Artisan Boulanger",
    type: "Bakery",
    foodType: "Bakery",
    price: 250,
    originalPrice: 600,
    image: "assets/images/Fresh-Matlouh-Hub.jpg",
    location: "Ouled Yaïch, Blida",
    timeLeft: "1 hour",
    description: "مطلوع السميد الطازج والدافئ، مثالي لتقديمه مع وجبات العشاء المنزلية.",
    promoted: false,
    paymentMethods: ["Cash"],
  },

  // --- MARKETS (10) ---
  {
    id: 31,
    title: "Grocery Essentials Box",
    donor: "Superette El Manar",
    type: "Market",
    foodType: "Healthy",
    price: 1200,
    originalPrice: 2000,
    image: "assets/images/supermarket-banner-with-food.jpg",
    location: "El Biar, Algiers",
    timeLeft: "2 days",
    description: "علبة تحتوي على أساسيات الطبخ: معكرونة، صلصة طماطم، ومعلبات متنوعة بجودة عالية.",
    promoted: false,
    paymentMethods: ["Cash", "BaridiMob"],
  },
  {
    id: 32,
    title: "Dairy & Cheese Bundle",
    donor: "Ardis Hypermarket",
    type: "Market",
    foodType: "Healthy",
    price: 3000,
    originalPrice: 2500,
    image: "assets/images/dairy-products.jpg",
    location: "Sidi Yahia, Algiers",
    timeLeft: "1 day",
    description: "حزمة من منتجات الألبان والأجبان الطازجة من أرديس، تشمل زبادي وأجبان متنوعة.",
    promoted: true,
    paymentMethods: ["CIB", "BaridiMob"],
  },
  {
    id: 33,
    title: "Fruit & Veg Basket",
    donor: "Uno Algiers",
    type: "Market",
    foodType: "Healthy",
    price: 800,
    originalPrice: 1800,
    image: "assets/images/mixed-vegetables-bucket-marble-background.jpg",
    location: "Bab Ezzouar, Algiers",
    timeLeft: "12 hours",
    description: "سلة خضروات وفواكه موسمية طازجة من أسواق أونو، منتقاة بعناية لضمان الجودة.",
    promoted: false,
    paymentMethods: ["Cash", "CIB"],
  },
  {
    id: 34,
    title: "Organic Pantry Box",
    donor: "Carrefour City",
    type: "Market",
    foodType: "Healthy",
    price: 2500,
    originalPrice: 4800,
    image: "assets/images/close-up-zero-waste-food-containers.jpg",
    location: "Ben Aknoun, Algiers",
    timeLeft: "3 days",
    description: "مجموعة منتجات عضوية تشمل عدس، حمص وزيت زيتون بكر من كارفور سيتي.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 35,
    title: "Bulk Pasta Pack",
    donor: "Mega Market",
    type: "Market",
    foodType: "Traditional",
    price: 1500,
    originalPrice: 3000,
    image: "assets/images/heap-raw-pasta-wooden-basket-marble-space.jpg",
    location: "Zouaghi, Constantine",
    timeLeft: "5 days",
    description: "حزمة اقتصادية من المعكرونة والكسكسي بوزن 5 كغ، مثالية للعائلات.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 36,
    title: "Snack & Drink Mix",
    donor: "Galaxy Market",
    type: "Market",
    foodType: "Fast Food",
    price: 1100,
    originalPrice: 2200,
    image: "assets/images/top-view-spicy-chips-bucket-with-corn-snacks-bucket-with-glass-orange-juice-with-sauce-green-bowl-wooden-table.jpg",
    location: "Centre Ville, Sétif",
    timeLeft: "2 days",
    description: "تشكيلة من المقرمشات، العصائر  للأطفال والعائلة.",
    promoted: false,
    paymentMethods: ["Cash", "BaridiMob"],
  },
  {
    id: 37,
    title: "Seafood Market Bag",
    donor: "Azur Market",
    type: "Market",
    foodType: "Healthy",
    price: 4500,
    originalPrice: 9000,
    image: "assets/images/Seafood-Market-Bag.jpg",
    location: "Port Area, Bejaia",
    timeLeft: "6 hours",
    description: "حقيبة من ثمار البحر الطازجة من ميناء بجاية، تشمل أنواعاً متنوعة من سمك اليوم.",
    promoted: true,
    paymentMethods: ["BaridiMob"],
  },
  {
    id: 38,
    title: "Meat & Poultry Pack",
    donor: "Mega Supermarché",
    type: "Market",
    foodType: "Traditional",
    price: 5200,
    originalPrice: 10500,
    image: "assets/images/female-hand-holds-container-with-meat-meat-supermarket.jpg",
    location: "Seddikia, Oran",
    timeLeft: "1 day",
    description: "حزمة من اللحوم الحمراء والدواجن الطازجة المقطعة والمجهزة للاستخدام الفوري.",
    promoted: true,
    paymentMethods: ["CIB", "BaridiMob"],
  },
  {
    id: 39,
    title: "Cleaning Supply Bundle",
    donor: "Superette El Kaws",
    type: "Market",
    foodType: "Healthy",
    price: 1800,
    originalPrice: 3500,
    image: "assets/images/close-up-person-holding-basket-with-cleaning-products.jpg",
    location: "Draria, Algiers",
    timeLeft: "15 days",
    description: "مجموعة منظفات منزلية تشمل صابون، سوائل تنظيف ومعقمات بجودة ممتازة.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 40,
    title: "Home & Garden Groceries",
    donor: "Prima Supermarché",
    type: "Market",
    foodType: "Healthy",
    price: 2600,
    originalPrice: 5000,
    image: "assets/images/vegetables-garden-sunlight.jpg",
    location: "Gambetta, Oran",
    timeLeft: "3 days",
    description: "سلة مواد استهلاكية متنوعة للمنزل من أرقى أنواع السوبر ماركت في وهران.",
    promoted: false,
    paymentMethods: ["Cash", "BaridiMob"],
  },

  // --- EVENTS & CATERING (10) ---
  {
    id: 41,
    title: "Wedding Buffet Surplus",
    donor: "Traiteur Royal",
    type: "Events & Catering",
    foodType: "Traditional",
    price: 2500,
    originalPrice: 6000,
    image: "assets/images/wedding-sweets-desserts.jpg",
    location: "Hydra, Algiers",
    timeLeft: "2 hours",
    description: "تشكيلة فاخرة من بوفيه حفل زفاف، تضم مقبلات ساخنة وأطباقاً رئيسية متنوعة محضرة بأيدي أمهر الطهاة.",
    promoted: true,
    paymentMethods: ["Cash"],
  },
  {
    id: 42,
    title: "Prestige Gala Dinner",
    donor: "Prestige Traiteur",
    type: "Events & Catering",
    foodType: "Traditional",
    price: 3500,
    originalPrice: 6000,
    image: "assets/images/dinner-table-setup-with-delicious-food-ready-be-served.jpg",
    location: "Les Falaises, Oran",
    timeLeft: "1.5 hours",
    description: "عرض خاص من عشاء غالا الفاخر، حصص سخية من الأطباق الراقية التي قدمت في أرقى المناسبات.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 43,
    title: "Constantine Feast Surplus",
    donor: "Constantine Catering",
    type: "Events & Catering",
    foodType: "Traditional",
    price: 2800,
    originalPrice: 6500,
    image: "assets/images/plate-with-fresh-food-near-cup-dried-fruits-burlap.jpg",
    location: "Djebel Ouahch, Constantine",
    timeLeft: "3 hours",
    description: "طعام قسنطيني ولحم الغنم المطهو ببطء، مثالية لجمعات العائلة.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 44,
    title: "Gourmet Appetizer Tray",
    donor: "Saveurs d'Algérie",
    type: "Events & Catering",
    foodType: "Fast Food",
    price: 1500,
    originalPrice: 3800,
    image: "assets/images/puff-pastry-mini-pizzas-with-sausages.jpg",
    location: "Zeralda, Algiers",
    timeLeft: "2 hours",
    description: "طبق مقبلات مشكل يضم ميني بيتزا تم تحضيرها لحفل استقبال فاخر.",
    promoted: true,
    paymentMethods: ["BaridiMob"],
  },
  {
    id: 45,
    title: "Elegant Dessert Platter",
    donor: "Délice Event",
    type: "Events & Catering",
    foodType: "Desserts",
    price: 1200,
    originalPrice: 3200,
    image: "assets/images/various-homemade-mini-tartlets-with-nuts-chocolate-cream.jpg",
    location: "Plaine Ouest, Annaba",
    timeLeft: "4 hours",
    description: "تشكيلة حلويات راقية تضم قطع الكيك الصغيرة والمقبلات الحلوة من أرقى خدمات الضيافة.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 46,
    title: "Setif Traditional Banquet",
    donor: "Traiteur El Hanna",
    type: "Events & Catering",
    foodType: "Traditional",
    price: 2200,
    originalPrice: 5500,
    image: "assets/images/assorted-meat-kebab-with-onions-herbs-grilled-vegetables.jpg",
    location: "Sétif Center, Sétif",
    timeLeft: "2.5 hours",
    description: "مائدة سطايفية تقليدية تضم أطباق اللحم المحمرة، محضرة للمناسبات الكبيرة.",
    promoted: true,
    paymentMethods: ["BaridiMob", "Cash"],
  },
  {
    id: 47,
    title: "Celebration Seafood Mix",
    donor: "L'Excellence Catering",
    type: "Events & Catering",
    foodType: "Traditional",
    price: 3800,
    originalPrice: 9500,
    image: "assets/images/closeup-shot-plate-seafood-christmas.jpg",
    location: "Port Area, Bejaia",
    timeLeft: "1 hour",
    description: "مزيج فاخر من الأسماك والجمبري من أرقى خدمات تقديم الطعام البحرية في بجاية.",
    promoted: true,
    paymentMethods: ["CIB"],
  },
  {
    id: 48,
    title: "Tlemcen Wedding Couscous",
    donor: "Noces et Banquets",
    type: "Events & Catering",
    foodType: "Traditional",
    price: 1800,
    originalPrice: 4500,
    image: "assets/images/Tlemcen-Wedding-Couscous.jpg",
    location: "Imama, Tlemcen",
    timeLeft: "4 hours",
    description: "كسكسي الأعراس التلمساني الملكي مع تشكيلة خضروات طازجة وحصص وافرة من اللحم.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 49,
    title: "South Algerian Roast",
    donor: "Traiteur du Sud",
    type: "Events & Catering",
    foodType: "Traditional",
    price: 4500,
    originalPrice: 12000,
    image: "assets/images/kharouf-machwi.jpg",
    location: "Ouargla City, Ouargla",
    timeLeft: "2 hours",
    description: "لحم الغنم المشوي بالطريقة الصحراوية (مشوي)، حصص سخية ومطهوة بإتقان.",
    promoted: true,
    paymentMethods: ["BaridiMob"],
  },
  {
    id: 50,
    title: "Mediterranean Mix Tray",
    donor: "Maghreb Events",
    type: "Events & Catering",
    foodType: "Healthy",
    price: 1400,
    originalPrice: 3500,
    image: "assets/images/wide-selection-marinated-fruits-vegetables-white-plate.jpg",
    location: "Centre Ville, Blida",
    timeLeft: "3.5 hours",
    description: "سلطات ومقبلات باردة متنوعة من حفل غداء راقٍ في قلب مدينة البليدة.",
    promoted: false,
    paymentMethods: ["Cash"],
  },

  // --- NGOs (10) ---
  {
    id: 51,
    title: "Fresh Vegetable Basket",
    donor: "Association Kafil El Yatim",
    type: "NGO",
    foodType: "Healthy",
    price: 300,
    originalPrice: 1000,
    image: "assets/images/top-view-basket-full-vegetables-white-surface.jpg",
    location: "Boufarik, Blida",
    timeLeft: "1 day",
    description: "سلة خضروات طازجة من مزارع الجمعية تذهب عائداتها لدعم الأيتام.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 52,
    title: "Solidarity Meal Pack",
    donor: "Croissant Rouge Algérien",
    type: "NGO",
    foodType: "Traditional",
    price: 0,
    originalPrice: 800,
    image: "assets/images/view-favourite-meal-set.jpg",
    location: "Sidi M'hamed, Algiers",
    timeLeft: "5 hours",
    description: "وجبات تضامنية ساخنة من تحضير متطوعي الهلال الأحمر الجزائري، مخصصة للفئات الهشة.",
    promoted: true,
    paymentMethods: ["Free"],
  },
  {
    id: 53,
    title: "Community Kitchen Box",
    donor: "Sidra Algeria",
    type: "NGO",
    foodType: "Healthy",
    price: 200,
    originalPrice: 1200,
    image: "assets/images/Community-Kitchen-Box.jpg",
    location: "El Biar, Algiers",
    timeLeft: "4 hours",
    description: "علب وجبات متوازنة من مبادرة 'مطبخ المجتمع' لجمعية سيدرة، لدعم الأمن الغذائي المحلي.",
    promoted: true,
    paymentMethods: ["Cash"],
  },
  {
    id: 54,
    title: "Patient Support Meal",
    donor: "Association El Badr",
    type: "NGO",
    foodType: "Healthy",
    price: 100,
    originalPrice: 6500,
    image: "assets/images/Patient-Support-Meal.jpg",
    location: "Plage Larbi Ben M'hidi, Skikda",
    timeLeft: "6 hours",
    description: "وجبات صحية ومغذية فائضة من مركز رعاية مرضى السرطان، محضرة بإشراف أخصائيي تغذية.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 55,
    title: "Ramadan Surplus Box",
    donor: "Ness El Khir",
    type: "NGO",
    foodType: "Healthy",
    price: 0,
    originalPrice: 2000,
    image: "assets/images/Ramadan-Surplus-Box.jpg",
    location: "Didouche Mourad, Algiers",
    timeLeft: "2 hours",
    description: "علبة متنوعة من المواد الغذائية المجمعة من تبرعات المؤسسات الكبرى، مخصصة للعائلات المحتاجة.",
    promoted: true,
    paymentMethods: ["Free"],
  },
  {
    id: 56,
    title: "Orphanage Breakfast Pack",
    donor: "Association SOS Enfants",
    type: "NGO",
    foodType: "Healthy",
    price: 150,
    originalPrice: 900,
    image: "assets/images/Orphanage-Breakfast-Pack.jpg",
    location: "Draria, Algiers",
    timeLeft: "3 hours",
    description: "حصص إفطار تشمل حليب، حبوب وفواكه فائضة من وجبة الصباح بدار الأيتام.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 57,
    title: "Welfare Food Bag",
    donor: "Association Dar El Insaniat",
    type: "NGO",
    foodType: "Healthy",
    price: 0,
    originalPrice: 1500,
    image: "assets/images/Welfare-Food-Bag.jpg",
    location: "Saint Hubert, Oran",
    timeLeft: "1 day",
    description: "حقيبة مواد غذائية جافة متنوعة موجهة لفائدة العائلات ذوات الدخل المحدود في منطقة وهران.",
    promoted: true,
    paymentMethods: ["Free"],
  },
  {
    id: 58,
    title: "Youth Hope Food Hub",
    donor: "Association Nadjah",
    type: "NGO",
    foodType: "Healthy",
    price: 300,
    originalPrice: 500,
    image: "assets/images/Youth-Hope-Food-Hub.jpg",
    location: "El Eulma, Sétif",
    timeLeft: "4 hours",
    description: "وجبات صحية خفيفة وسلطات طازجة مخصصة لدعم نشاط الشباب وتحفيزهم على العمل التطوعي.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 59,
    title: "Islamic Relief Meal",
    donor: "Association El Irchad",
    type: "NGO",
    foodType: "Traditional",
    price: 200,
    originalPrice: 1000,
    image: "assets/images/Islamic-Relief-Meal.jpg",
    location: "Hamma Bouziane, Constantine",
    timeLeft: "5 hours",
    description: "وجبات كسكسي تقليدية دافئة يتم توزيعها في إطار مبادرات الإطعام التكافلي لجمعية الإرشاد.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 60,
    title: "Coastal Aid Basket",
    donor: "Association Salsabil",
    type: "NGO",
    foodType: "Healthy",
    price: 100,
    originalPrice: 1200,
    image: "assets/images/Sea-fruits.jpg",
    location: "Plaine Ouest, Annaba",
    timeLeft: "8 hours",
    description: " ثمار البحر المقدمة كمساهمة تضامنية من الصيادين المحليين لتوزيعها على المحتاجين.",
    promoted: true,
    paymentMethods: ["Cash"],
  },
];

const categories = [
  { name: "Restaurants", icon: "fas fa-utensils", link: "restaurants.html" },
  { name: "Hotels", icon: "fas fa-hotel", link: "hotels.html" },
  { name: "Bakeries", icon: "fas fa-bread-slice", link: "bakeries.html" },
  { name: "Markets", icon: "fas fa-carrot", link: "markets.html" },
  { name: "Events & Catering", icon: "fas fa-glass-cheers", link: "events-catering.html" },
  { name: "NGOs", icon: "fas fa-hand-holding-heart", link: "ngo.html" },
];
