const foodItems = [
  {
    id: 1,
    title: "Plateau Gâteaux Traditionnels",
    donor: "Maison Amoud",
    type: "Bakery",
    price: 1500,
    originalPrice: 2500,
    image: "https://images.unsplash.com/photo-1559500186-6361a94a4855?auto=format&fit=crop&w=800&q=80", // Baklava
    location: "Sidi Yahia, Algiers",
    timeLeft: "2 hours",
    description: "Box of baklava, makrout, and tcharek. Homemade style and delicious.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB"],
  },
  {
    id: 2,
    title: "Pizza Carrée & Coca",
    donor: "Pizzeria L'Etna",
    type: "Restaurant",
    price: 600,
    originalPrice: 1200,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80", // Pizza
    location: "8 Bd de la Soummam, Oran",
    timeLeft: "4 hours",
    description: "Square pizza and hot Coca-Cola, full of cheese and olives.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 3,
    title: "Mhajeb Hot Box",
    donor: "Marriott Constantine Protégé",
    type: "Hotel",
    price: 800,
    originalPrice: 2000,
    image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=800&q=80", // Flatbread/Mhajeb visual
    location: "Cité universitaire Zouaghi, Constantine",
    timeLeft: "1 hour",
    description: "Spicy and hot Mhajeb box, leftover from breakfast buffet.",
    promoted: true,
    paymentMethods: ["BaridiMob", "CIB", "Cash"],
  },
  {
    id: 4,
    title: "Fresh Vegetable Basket",
    donor: "Association Kafil El Yatim",
    type: "NGO",
    price: 300,
    originalPrice: 1000,
    image: "https://images.unsplash.com/photo-1566385101042-1a0aa0c1268c?auto=format&fit=crop&w=800&q=80", // Vegetables
    location: "Boufarik, Blida",
    timeLeft: "1 day",
    description: "Fresh vegetables from the garden: tomatoes, cucumbers, and carrots.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
  {
    id: 5,
    title: "Couscous Royal",
    donor: "Restaurant Le Nautique",
    type: "Restaurant",
    price: 1800,
    originalPrice: 4500,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80", // Couscous
    location: "Route du Cap de Garde, Annaba",
    timeLeft: "30 mins",
    description: "Royal Couscous with meat and vegetables, premium quality.",
    promoted: true,
    paymentMethods: ["CIB", "BaridiMob"],
  },
  {
    id: 6,
    title: "Matlouh & Kesra",
    donor: "Boulangerie El Baraka",
    type: "Bakery",
    price: 200,
    originalPrice: 500,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80", // Bread
    location: "El Eulma, Sétif",
    timeLeft: "3 hours",
    description: "Matlouh and Kesra, hot and fresh from the oven.",
    promoted: false,
    paymentMethods: ["Cash"],
  },
];

const categories = [
  { name: "Restaurants", icon: "fas fa-utensils", link: "restaurants.html" },
  { name: "Hotels", icon: "fas fa-hotel", link: "hotels.html" },
  { name: "Bakeries", icon: "fas fa-bread-slice", link: "bakeries.html" },
  { name: "Events & Catering", icon: "fas fa-glass-cheers", link: "events-catering.html" },
  { name: "NGOs", icon: "fas fa-hand-holding-heart", link: "ngo.html" },
];
